# Generated by Django 2.2 on 2019-12-18 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='cars',
        ),
        migrations.AddField(
            model_name='employee',
            name='car',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='cars.Car'),
            preserve_default='true',
        ),
    ]
